### ISSUE TITLE
QueryWatcher works in window but not as a replicant

### ISSUE THREAD

**Issue by ilfelice** [HaikuArchives/QueryWatcher#5]
QueryWatcher works well when run in a window.

![screenshot-1](https://user-images.githubusercontent.com/102931400/213316256-17b233f2-3654-4d59-8ea6-698184453d24.png)

However, when you drag and drop the replicant hand on the desktop, the resulting replicant is an empty widget.

![screenshot-2](https://user-images.githubusercontent.com/102931400/213316264-02dc0bf7-af83-48e0-a4b8-f0d860a13944.png)

Right-clicking on the replicant hand shows that the widget is a zombie window. The "About <Zombie>" right-click menu displays an error message (see screenshot ).

![screenshot-3](https://user-images.githubusercontent.com/102931400/213316269-88527004-20f7-4f13-badc-3aca588cd3df.png)

**Comment by humdingerb** [comment]
Already reported with #3. :)

**Comment by ilfelice** [comment]
@humdingerb 

You are right. Would it help adding the details with images to #3 ?

**Comment by humdingerb** [comment]
I don't think so. If someone investigates this, it's easy to reproduce and hard to miss...
But I'll leave a comment pointing to this issue at #5 nonetheless.

**Comment by ilfelice** [comment]
> I don't think so. If someone investigates this, it's easy to reproduce and hard to miss...
> But I'll leave a comment pointing to this issue at #5 nonetheless.

Thank you! And sorry for the extra work that I may have caused. m(_ _)m

**Comment by humdingerb** [comment]
No problem. A duplicate closed is better than a bug not reported. :)
